// ------------------------------------------------------------------------------------------------
// Training ~ A training program for new joinees at Metamation, Batch- July 2025.
// Copyright (c) Metamation India.
// ------------------------------------------------------------------
// Program.cs
// Program to guess a randomly generated number or let the computer guess our number
// ------------------------------------------------------------------------------------------------
using static System.Console;

// Get a Yes/No from the user with a single key input
EChoice GetChoice () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.Y: return EChoice.Yes;
         case ConsoleKey.N: return EChoice.No;
         case ConsoleKey.Escape: return EChoice.Previous_menu;
         default: Write ($"\n{ValidInput ("Y,N or EsC")}"); break;
      }
}

// Gets the guessing mode from the user with a single key input
EMode GetMode () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.C: return EMode.Computer_Guess;
         case ConsoleKey.U: return EMode.User_Guess;
         default: Write ($"\n{ValidInput ("C or U")}"); break;
      }
}

// Gets the computer guessing method from the user with a single key input
EMethod GetMethod () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.M: return EMethod.MSB;
         case ConsoleKey.L: return EMethod.LSB;
         default: Write ($"\n{ValidInput ("M or L")}"); break;
      }
}

// Main program
WriteLine ("Select the game mode:\n-> (C)omputer guess\n-> (U)ser guess");
var mode = GetMode ();
WriteLine (mode);
if (mode is EMode.User_Guess) UserGuess ();
else {
   WriteLine ("Assume a number in the range 0 - 127.");
   while (true) {
      Console.Write ("Choose the guessing method, (M)SB or (L)SB: ");
      var method = GetMethod ();
      WriteLine (method);
      int finalGuess = (method is EMethod.MSB) ? GuessMSB () : GuessLSB ();
      if (finalGuess is -1) continue;
      WriteLine ($"Your number is {finalGuess}"); break;
   }
}

// Makes the user guess a random number generated by the computer
void UserGuess () {
   int guess, num = new Random ().Next (1, 101);
   Write ("Guess the number between 1 and 100: ");
   while (true) {
      while (!int.TryParse (ReadLine (), out guess) || guess is < 0 or > 100)
         Write ($"\n{ValidInput ("a positive number within the given range")}");
      if (guess == num) break;
      Write ($"Your guess is too {((guess > num) ? "high" : "low")}. Try again: ");
   }
   WriteLine ("You guessed correctly !!");
}

// Makes the computer guess the user's number from the MSB to LSB
int GuessMSB () {
   (int upper, int lower, int ans) = (128, 0, 0);
   for (int i = 0; i < 7; i++) {
      int mid = (upper + lower) / 2;
      Write ($"Is the number less than {mid}? (Y)es, (N)o, (Esc)Previous menu: ");
      var choice = GetChoice ();
      WriteLine (choice);
      switch (choice) {
         case EChoice.Previous_menu: return -1;
         case EChoice.Yes: upper = mid; break;
         default: ans |= 1 << (6 - i); lower = mid; break;
      }
   }
   return ans;
}

// Makes the computer guess the user's number from the LSB to MSB
int GuessLSB () {
   int ans = 0;
   for (int i = 0; i < 7; i++) {
      int div = 1 << (i + 1);
      int mod = ans % div;
      Write ($"When the number is divided by {div}, is the remainder {mod}? (Y)es, (N)o, (Esc)Previous menu: ");
      var choice = GetChoice ();
      WriteLine (choice);
      switch (choice) {
         case EChoice.Previous_menu: return -1;
         case EChoice.No: ans |= 1 << i; break;
         default: break;
      }
   }
   return ans;

}

// Returns an invalid message with the acceptable inputs
string ValidInput (string s) => $"Please enter only {s}: ";

enum EChoice { Yes, No, Previous_menu }
enum EMode { Computer_Guess, User_Guess }
enum EMethod { MSB, LSB }