// ------------------------------------------------------------------------------------------------
// Training ~ A training program for new joinees at Metamation, Batch- July 2025.
// Copyright (c) Metamation India.
// ------------------------------------------------------------------
// Program.cs
// Program to guess a randomly generated number or let the computer guess our number
// ------------------------------------------------------------------------------------------------
using static System.Console;

string invalidMsg = "Please enter a valid input: ";

// Get a Yes/No from the user with a single key input
EChoice GetChoice () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.Y: return EChoice.Yes;
         case ConsoleKey.N: return EChoice.No;
         case ConsoleKey.Escape: return EChoice.Undo;
         default: Write (invalidMsg); break;
      }
}

// Gets the guessing mode from the user with a single key input
EMode GetMode () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.C: return EMode.Computer_Guess;
         case ConsoleKey.U: return EMode.User_Guess;
         default: Write (invalidMsg); break;
      }
}

// Gets the computer guessing method from the user with a single key input
EMethod GetMethod () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.M: return EMethod.MSB;
         case ConsoleKey.L: return EMethod.LSB;
         default: Write (invalidMsg); break;
      }
}

// Main program
WriteLine ("Select the game mode:\n-> (C)omputer guess\n-> (U)ser guess");
var mode = GetMode ();
WriteLine (mode);
if (mode is EMode.User_Guess) UserGuess ();
else {
   Write ("Choose the guessing method, (M)SB or (L)SB: ");
   var method = GetMethod ();
   WriteLine (method);
   int finalGuess = (method is EMethod.MSB) ? GuessMSB () : GuessLSB ();
   WriteLine ($"Your number is {finalGuess}");
}

// Makes the user guess a random number generated by the computer
void UserGuess () {
   int guess;
   Write ("Guess the number between 1 and 100: ");
   int num = new Random ().Next (1, 101);
   while (true) {
      while (!int.TryParse (ReadLine (), out guess) || guess is < 0 or > 100) Write (invalidMsg);
      if (guess == num) break;
      Write ($"Your guess is too {((guess > num) ? "high" : "low")}. Try again: ");
   }
   WriteLine ("You guessed correctly !!");
}

// Makes the computer guess the user's number from the MSB to LSB
int GuessMSB () {
   (int upper, int lower, int ans, int i) = (128, 0, 0, 0);
   (int, int, int, int) prev = (upper, lower, ans, i);
   while (i < 7) {
      int mid = (upper + lower) / 2;
      Write ($"Is the number less than {mid}? (Y)es, (N)o, (Esc)Undo: ");
      var choice = GetChoice ();
      WriteLine (choice);
      if (choice is EChoice.Undo) {
         (upper, lower, ans, i) = prev;
         continue;
      }
      prev = (upper, lower, ans, i);
      if (choice is EChoice.Yes) upper = mid;
      else {
         ans |= 1 << (6 - i);
         lower = mid;
      }
      i++;
   }
   return ans;
}

// Makes the computer guess the user's number from the LSB to MSB
int GuessLSB () {
   (int ans, int i) = (0, 0);
   (int, int) prev = (ans, i);
   while (i < 7) {
      int divisor = 1 << (i + 1);
      int remainder = ans % divisor;
      Write ($"When the number is divided by {divisor}, is the remainder {remainder}? (Y)es, (N)o, (Esc)Undo: ");
      var choice = GetChoice ();
      WriteLine (choice);
      if (choice is EChoice.Undo) {
         (ans, i) = prev;
         continue;
      }
      prev = (ans, i);
      if (choice is EChoice.No) ans |= 1 << i;
      i++;
   }
   return ans;
}

enum EChoice { Yes, No, Undo }
enum EMode { Computer_Guess, User_Guess }
enum EMethod { MSB, LSB }