// ------------------------------------------------------------------------------------------------
// Training ~ A training program for new joinees at Metamation, Batch- July 2025.
// Copyright (c) Metamation India.
// ------------------------------------------------------------------
// Program.cs
// Program to guess a randomly generated number or let the computer guess our number
// ------------------------------------------------------------------------------------------------
using static System.Console;

// Get a Yes/No from the user with a single key input
EChoice GetChoice () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.Y: return EChoice.Yes;
         case ConsoleKey.N: return EChoice.No;
         case ConsoleKey.Escape: return EChoice.Previous_question;
         default: Write (ValidInput ("Y,N or EsC")); break;
      }
}

// Gets the guessing mode from the user with a single key input
EMode GetMode () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.C: return EMode.Computer_Guess;
         case ConsoleKey.U: return EMode.User_Guess;
         default: Write (ValidInput ("C or U")); break;
      }
}

// Gets the computer guessing method from the user with a single key input
EMethod GetMethod () {
   while (true)
      switch (ReadKey (true).Key) {
         case ConsoleKey.M: return EMethod.MSB;
         case ConsoleKey.L: return EMethod.LSB;
         default: Write (ValidInput ("M or L")); break;
      }
}

// Main program
WriteLine ("Select the game mode:\n-> (C)omputer guess\n-> (U)ser guess");
var mode = GetMode ();
WriteLine (mode);
if (mode is EMode.User_Guess) UserGuess ();
else {
   Write ("Assume a number in the range 0 - 127.\nChoose the guessing method, (M)SB or (L)SB: ");
   var method = GetMethod ();
   WriteLine (method);
   int finalGuess = (method is EMethod.MSB) ? GuessMSB () : GuessLSB ();
   WriteLine ($"Your number is {finalGuess}");
}

// Makes the user guess a random number generated by the computer
void UserGuess () {
   int guess;
   Write ("Guess the number between 1 and 100: ");
   int num = new Random ().Next (1, 101);
   while (true) {
      while (!int.TryParse (ReadLine (), out guess) || guess is < 0 or > 100)
         Write (ValidInput ("a positive number within the given range"));
      if (guess == num) break;
      Write ($"Your guess is too {((guess > num) ? "high" : "low")}. Try again: ");
   }
   WriteLine ("You guessed correctly !!");
}

// Makes the computer guess the user's number from the MSB to LSB
int GuessMSB () {
   (int upper, int lower, int ans, int i) = (128, 0, 0, 0);
   (int, int, int, int) prev = (upper, lower, ans, i);
   while (i < 7) {
      int mid = (upper + lower) / 2;
      Write ($"Is the number less than {mid}? (Y)es, (N)o, (Esc)Previous question: ");
      var choice = GetChoice ();
      WriteLine (choice);
      switch (choice) {
         case EChoice.Previous_question: (upper, lower, ans, i) = prev; continue;
         case EChoice.Yes: SavePrev (); upper = mid; break;
         default: SavePrev (); ans |= 1 << (6 - i); lower = mid; break;
      }
      i++;
   }
   return ans;

   void SavePrev () => prev = (upper, lower, ans, i);
}

// Makes the computer guess the user's number from the LSB to MSB
int GuessLSB () {
   (int ans, int i) = (0, 0);
   (int, int) prev = (ans, i);
   while (i < 7) {
      int div = 1 << (i + 1);
      int mod = ans % div;
      Write ($"When the number is divided by {div}, is the remainder {mod}? (Y)es, (N)o, (Esc)Previous question: ");
      var choice = GetChoice ();
      WriteLine (choice);
      switch (choice) {
         case EChoice.Previous_question: (ans, i) = prev; continue;
         case EChoice.No: SavePrev (); ans |= 1 << i; break;
         default: SavePrev (); break;
      }
      i++;
   }
   return ans;

   void SavePrev () => prev = (ans, i);
}

// Returns an invalid message with the acceptable inputs
string ValidInput (string s) => $"Please enter only {s}: ";

enum EChoice { Yes, No, Previous_question }
enum EMode { Computer_Guess, User_Guess }
enum EMethod { MSB, LSB }